//开发模式
   document.write("\<script type='text/javascript' src='../../modules/jquery-1.7.2.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/bootstrap/bootstrap.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/JSON.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/Type.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/GUID.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/Base64.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/DatePack.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/util/Ver.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/plugins/Notice.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/plugins/Noty.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/plugins/Message.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/plugins/WinForm.js'\>\<\/script\>");
// document.write("\<script type='text/javascript' src='../../modules/plugins/Search.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/plugins/Verify.js'\>\<\/script\>");
// document.write("\<script type='text/javascript' src='../../modules/plugins/Tel.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/tn/TN.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/tn/pinyinEngine.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/tn/TNQuoteGridPanel/TNQuoteGridPanel.js'\>\<\/script\>");
   document.write("\<script type='text/javascript' src='../../modules/tn/TNSearch/TNSearch.js'\>\<\/script\>");
